<?php

/**
 * @file
 * Contains skvare_documentation.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function skvare_documentation_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the skvare_documentation module.
    case 'help.page.skvare_documentation':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module providing standard Skvare documentation functionality') . '</p>';
      return $output;

    default:
  }
}
