email_verification.settings:
  type: config_object
  label: 'Email Verification Settings'
  mapping:
    user_email_verification_salt:
      type: text
      label: 'Random key to generate verify email hash'
    user_email_verification_tpl:
      type: textarea
      label: 'User Verification Email Template'
    user_email_verification_helptext:
      type: text_format
      label: 'User Verification Help Text'
