<?php

/**
 * @file
 * Banner Slideshow Skvare module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function banner_slideshow_skvare_preprocess_block(&$variables) {
  // Add class and attach library for blocks of type Banner Slideshow.
  if (!empty($variables['content']['#block_content']) && $variables['content']['#block_content']->bundle() == 'banner_slideshow') {
    $variables['#attached']['library'][] = 'banner_slideshow_skvare/banner-slideshow';
    $variables['attributes']['class'][] = 'block-type-banner-slideshow';
  }
}
